# Generated by Django 5.1rc1 on 2024-08-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationform',
            name='time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
