# Generated by Django 5.0.7 on 2024-07-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_pharm_roll_no', models.CharField(blank=True, max_length=100, null=True)),
                ('m_pharm_roll_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('name_of_spouse', models.CharField(blank=True, max_length=150, null=True)),
                ('marriage_date', models.DateField()),
                ('no_of_kids', models.IntegerField(blank=True, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=150, null=True)),
                ('Present_address', models.CharField(max_length=250, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=250, null=True)),
                ('designation_and_department', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
