# Generated by Django 5.1rc1 on 2024-08-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userregistrationform_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationform',
            name='time_limit',
        ),
    ]
