# Generated by Django 5.0.7 on 2024-07-31 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userregistrationform_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationform',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
