# Generated by Django 5.1rc1 on 2024-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='payment_getway',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Demand_Draft', 'Demand Draft'), ('pay_order', 'Pay Order'), ('online_pay', 'Online Pay')], max_length=200, null=True),
        ),
    ]
