# Generated by Django 5.1 on 2024-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userregistrationform_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationform',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
