# Generated by Django 5.1rc1 on 2024-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paymentinformation_payment_getway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_getway',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('demand_draft', 'Demand Draft'), ('pay_order', 'Pay Order'), ('online_pay', 'Online Pay')], max_length=200, null=True),
        ),
    ]
