# Generated by Django 5.0.7 on 2024-07-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_present_address_userregistrationform_present_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationform',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistrationform',
            name='marriage_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
