# Generated by Django 5.1rc1 on 2024-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paymentinformation_payment_getway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
