# Generated by Django 5.1rc1 on 2024-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentinformation_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('renewal', 'Renewal')], max_length=200, null=True),
        ),
    ]
