# Generated by Django 5.0.7 on 2024-07-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userregistrationform_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationform',
            old_name='person',
            new_name='user',
        ),
    ]
