# Generated by Django 5.1 on 2024-08-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_end_time_userregistrationform_active_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminregister',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminregister',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
