# Generated by Django 5.1 on 2024-08-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminregister_registration_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationform',
            old_name='active_since',
            new_name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='adminregister',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='adminregister',
            name='start_date',
        ),
        migrations.AddField(
            model_name='userregistrationform',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
