# Generated by Django 5.0.7 on 2024-08-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user-default/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
