# Generated by Django 5.0.8 on 2024-08-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_active_since_userregistrationform_registration_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationform',
            old_name='registration_deadline',
            new_name='status_set_at',
        ),
        migrations.RemoveField(
            model_name='userregistrationform',
            name='start_date',
        ),
        migrations.AddField(
            model_name='userregistrationform',
            name='status_expiry_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
