# Generated by Django 5.0.8 on 2024-08-13 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_registration_deadline_userregistrationform_status_set_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationform',
            name='status_expiry_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=180)),
        ),
    ]
