# Generated by Django 5.0.7 on 2024-08-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregister',
            name='is_publish',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='publish'),
        ),
    ]
