# Generated by Django 5.0.8 on 2024-08-13 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userregistrationform_status_expiry_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationform',
            name='status_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='userregistrationform',
            name='status_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
