# Generated by Django 5.0.8 on 2024-08-13 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userregistrationform_status_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationform',
            name='status_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=120)),
        ),
    ]
