# Generated by Django 5.0.7 on 2024-08-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_address_remove_user_b_pharm_roll_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationform',
            old_name='address',
            new_name='organization_address',
        ),
    ]
