# Generated by Django 5.0.8 on 2024-08-13 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userregistrationform_status_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationform',
            name='status_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
