# Generated by Django 5.0.8 on 2024-08-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userregistrationform_status_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationform',
            old_name='status_set_at',
            new_name='last_activated',
        ),
        migrations.RemoveField(
            model_name='userregistrationform',
            name='status_duration',
        ),
    ]
