# Generated by Django 5.0.7 on 2024-08-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvupload',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
